# Generated by Django 5.1.4 on 2024-12-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_profile_address_profile_bio_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
