# Generated by Django 5.1.4 on 2024-12-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_discount_product_is_featured_product_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={},
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
