# Generated by Django 5.1.4 on 2024-12-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_saleslead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesLead',
        ),
    ]
